(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.YeogiroNotify=factory()})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const DEFAULTS=Object.freeze({departure:true,schedule:true,weather:true,preTrip:true,morning:false});
const OUTDOOR=/해변|공원|관광|야시장|트레킹|투어|산|테마파크|야외|골프|서핑|스키/i;
function timeMinutes(value){if(!/^\d{2}:\d{2}$/.test(String(value||'')))return null;const[h,m]=value.split(':').map(Number);return h<24&&m<60?h*60+m:null}
function stableId(tripId,targetId,type,stamp=''){return[tripId,targetId,type,stamp].filter(Boolean).join(':')}
function normalizeSettings(value={}){return{...DEFAULTS,...Object.fromEntries(Object.keys(DEFAULTS).map(key=>[key,value[key]===undefined?DEFAULTS[key]:Boolean(value[key])]))}}
function scheduleReminderMinutes(item){const value=Number(item?.reminderMinutes);return[10,30,60].includes(value)?value:0}
function due(now,target,windowMinutes=1){return target<=now&&target>now-windowMinutes}
function itemEvents({tripId,day,nowMinutes,items=[],legs={},settings=DEFAULTS,windowMinutes=1}){const config=normalizeSettings(settings),sorted=items.filter(x=>x.day===day&&timeMinutes(x.time)!==null).sort((a,b)=>a.time.localeCompare(b.time)),events=[];
for(let index=0;index<sorted.length;index++){const item=sorted[index],start=timeMinutes(item.time),reminder=scheduleReminderMinutes(item),previous=sorted[index-1],leg=legs[item.id],travel=Number(leg?.durationMinutes),prep=Math.max(0,Number(item.preparationMinutes)||0),departure=Number.isFinite(travel)?start-travel-prep:null;
if(config.schedule&&reminder&&due(nowMinutes,start-reminder,windowMinutes))events.push({id:stableId(tripId,item.id,'schedule',`${day}-${start-reminder}`),type:'schedule',targetId:item.id,at:start-reminder,title:`${reminder}분 후 ${item.name}이 시작됩니다.`,body:[item.place,item.time].filter(Boolean).join(' · '),url:`/?notify=item&id=${encodeURIComponent(item.id)}`});
if(config.departure&&previous&&departure!==null&&due(nowMinutes,departure,windowMinutes))events.push({id:stableId(tripId,item.id,'departure',`${day}-${departure}`),type:'departure',targetId:item.id,at:departure,title:`${item.name}${/[으로로]$/.test(item.name)?'':'로'} 이동할 시간이에요`,body:`${leg.label||item.move||'이동'} 약 ${travel}분 · 지금 출발하면 여유 있게 도착할 수 있어요.`,url:`/?notify=departure&id=${encodeURIComponent(item.id)}`});
}
return mergeCollisions(events)}
function overdueEvent({tripId,day,nowMinutes,item,leg,previous,settings=DEFAULTS,maxLateMinutes=15}){if(!normalizeSettings(settings).departure||!item||!previous)return null;const start=timeMinutes(item.time),travel=Number(leg?.durationMinutes);if(start===null||!Number.isFinite(travel))return null;const departure=start-travel-Math.max(0,Number(item.preparationMinutes)||0),late=nowMinutes-departure;if(late<=0||late>maxLateMinutes||nowMinutes>=start)return null;return{id:stableId(tripId,item.id,'departure-late',day),type:'departure',targetId:item.id,at:nowMinutes,title:'지금 출발하는 것이 좋습니다.',body:`${item.name}까지 ${leg.label||item.move||'이동'} 약 ${travel}분`,url:`/?notify=departure&id=${encodeURIComponent(item.id)}`}}
function mergeCollisions(events){const groups=new Map;for(const event of events){const key=`${event.targetId}:${event.at}`,group=groups.get(key)||[];group.push(event);groups.set(key,group)}return[...groups.values()].map(group=>{if(group.length===1)return group[0];const departure=group.find(x=>x.type==='departure'),schedule=group.find(x=>x.type==='schedule'),base=departure||group[0];return{...base,id:stableId(base.id.split(':')[0],base.targetId,'combined',String(base.at)),type:'combined',title:'곧 이동할 시간이에요',body:[schedule?.body?.split(' · ').at(-1),departure?.body?.split(' · ').slice(0,1)].filter(Boolean).join(' · ')}})}
function significantWeatherChange(previous,current,item){if(!item||!OUTDOOR.test(`${item.name||''} ${item.cat||''} ${item.memo||''}`))return null;const before=Number(previous?.precipitationProbability)||0,after=Number(current?.precipitationProbability)||0,wind=Number(current?.windSpeed)||0,feels=Number(current?.apparentTemperature);if(after>=70&&after-before>=30)return{kind:'rain',title:'일정 시간대에 비 가능성이 높아요',body:`${item.name} 방문 시 우산을 챙겨주세요.`};if(wind>=45&&(Number(previous?.windSpeed)||0)<35)return{kind:'wind',title:'일정 시간대에 바람이 강할 수 있어요',body:`${item.name} 운영 여부를 확인해 주세요.`};if(feels>=35&&(Number(previous?.apparentTemperature)||0)<33)return{kind:'heat',title:'야외 일정 시간대가 매우 더울 수 있어요',body:`${item.name} 방문 전 물과 휴식을 준비해 주세요.`};return null}
function pruneHistory(history={},validIds=null,limit=120){const entries=Object.entries(history).filter(([id])=>!validIds||validIds.has(id)).sort((a,b)=>Number(b[1])-Number(a[1])).slice(0,limit);return Object.fromEntries(entries)}
function pending(events,history={},now=Date.now(),dedupeMs=36*60*60*1000){return events.filter(event=>!history[event.id]||now-Number(history[event.id])>dedupeMs)}
return{DEFAULTS,timeMinutes,stableId,normalizeSettings,scheduleReminderMinutes,itemEvents,overdueEvent,mergeCollisions,significantWeatherChange,pruneHistory,pending};
});
