(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.YeogiroPrep=factory()})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const COMMON=[['항공권',true],['숙소 예약',true],['여행자보험',false],['충전기',false],['상비약',false],['세면도구',false]];
const INTERNATIONAL=[['여권',true],['환전/해외결제 카드',true],['eSIM/로밍',false]];
const KOREAN=/서울|부산|제주|인천|대구|대전|광주|울산|경주|강릉|속초|전주|여수|한국|대한민국/;
function internationalTrip(trip){const cities=(trip?.cities||[]).join(' ').trim();if(!cities)return null;return !KOREAN.test(cities)}
function template(trip,idFactory=()=>crypto.randomUUID()){const foreign=internationalTrip(trip),rows=[...COMMON,...(foreign===true?INTERNATIONAL:[])];return rows.map(([title,important],index)=>({id:idFactory(),title,scope:'personal',assigneeMemberId:'',completed:false,sortOrder:index,important}))}
function normalize(items=[]){return items.filter(x=>x&&x.id&&String(x.title||'').trim()).map((x,index)=>({id:String(x.id),title:String(x.title).trim().slice(0,100),scope:x.scope==='shared'?'shared':'personal',assigneeMemberId:x.scope==='shared'?String(x.assigneeMemberId||''):'',completed:Boolean(x.completed),sortOrder:Number.isFinite(Number(x.sortOrder))?Number(x.sortOrder):index,important:Boolean(x.important)})).sort((a,b)=>a.sortOrder-b.sortOrder||a.title.localeCompare(b.title))}
function progress(items=[],personalState={}){const list=normalize(items),done=list.filter(x=>x.scope==='personal'?Boolean(personalState[x.id]):x.completed).length;return{done,total:list.length,percent:list.length?Math.round(done/list.length*100):0}}
function documents(trip){return[...(trip.items||[]),...(trip.flights||[]),...(trip.lodgings||[])].flatMap(x=>x.userDocs||[])}
function checks(trip,{weather=null}={}){const flights=trip.flights||[],lodgings=trip.lodgings||[],docs=documents(trip),results=[],add=(id,label,ok,optional=false,action='')=>results.push({id,label,ok:Boolean(ok),optional:Boolean(optional),action});add('dates','여행 날짜가 올바릅니다.',Boolean(trip.start&&trip.end&&trip.end>=trip.start),false,'trip');add('cities',trip.cities?.length?'방문 도시가 등록되었습니다.':'방문 도시를 추가하면 날씨와 이동이 더 정확해집니다.',trip.cities?.length,true,'trip');add('flights',flights.length?'항공편이 등록되었습니다.':'항공편 미등록 · 필요한 경우 추가하세요.',flights.length,true,'flight');for(const flight of flights){const missing=[['departDate','출발일'],['depart','출발시간'],['from','출발 공항'],['to','도착 공항']].filter(([key])=>!flight[key]).map(x=>x[1]);if(missing.length)add(`flight-${flight.id}`,`항공편 ${missing.join('·')}을 확인해 주세요.`,false,false,'flight');if(!(flight.userDocs||[]).length)add(`flight-doc-${flight.id}`,'항공편 예약서류가 연결되지 않았습니다.',false,true,'documents')}
add('lodgings',lodgings.length?'숙소가 등록되었습니다.':'숙소 미등록 · 필요한 날짜를 확인해 보세요.',lodgings.length,true,'lodging');for(const lodging of lodgings){if(!lodging.address)add(`lodging-address-${lodging.id}`,'숙소 주소를 확인해 주세요.',false,true,'lodging');if(lodging.checkOutDate<lodging.checkInDate)add(`lodging-date-${lodging.id}`,'숙소 체크아웃 날짜가 체크인보다 빠릅니다.',false,false,'lodging');if(!(lodging.userDocs||[]).length)add(`lodging-doc-${lodging.id}`,'숙소 예약서류가 연결되지 않았습니다.',false,true,'documents')}
add('documents',docs.length?`예약서류 ${docs.length}건이 연결되었습니다.`:'예약서류 없음 · 선택 사항',docs.length,true,'documents');add('first-day',(trip.items||[]).some(x=>x.day===trip.start)?'첫날 일정이 등록되었습니다.':'첫날 일정 없음 · 자유 일정이라면 그대로 두세요.',(trip.items||[]).some(x=>x.day===trip.start),true,'schedule');add('currency',`기준 통화 ${trip.expenseSettings?.baseCurrency||'KRW'}`,Boolean(trip.expenseSettings?.baseCurrency),false,'expense');add('budget',trip.expenseSettings?.budgetMinor!=null?'여행 예산이 설정되었습니다.':'예산 미설정 · 선택 사항',trip.expenseSettings?.budgetMinor!=null,true,'expense');add('weather',weather?.available?weather.label:'첫날 날씨는 아직 예보 범위가 아닙니다.',Boolean(weather?.available),true,'weather');return results}
function summary(trip,items,personalState={},weather=null){const p=progress(items,personalState);return{flights:(trip.flights||[]).length,lodgings:(trip.lodgings||[]).length,documents:documents(trip).length,done:p.done,total:p.total,weather:weather?.label||''}}
return{COMMON,INTERNATIONAL,internationalTrip,template,normalize,progress,checks,summary};
});
