import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync('index.html', 'utf8');
const worker = readFileSync('worker.js', 'utf8');

assert.equal((source.match(/function shareSettings/g) || []).length, 1, '공유 관리 화면 구현은 하나만 존재');
assert.equal((source.match(/function recoverSheet/g) || []).length, 1, '여행 복구 화면 구현은 하나만 존재');
assert.equal((source.match(/function recoveryResult/g) || []).length, 1, '복구 코드 결과 화면 구현은 하나만 존재');
assert.doesNotMatch(source, /shareSettings\s*=\s*async|recoverSheet\s*=|recoveryResult\s*=/, '함수 재할당 오버라이드 제거');
assert.doesNotMatch(source, /소유권 복구키|복구키 재발급|동행자|소유권 이전/, '이전 사용자 용어 제거');
assert.match(source, /function roleName\(role\)\{return role==='owner'\?'관리자'/, '소유자 역할을 관리자 용어로 표시');
assert.match(source, /\['소유자','여행 관리자'\]\.includes\(m\.display_name\)\?'관리자'[\s\S]*<h3>구성원<\/h3>/, '구성원 제목과 기존 관리자 이름 호환 표시');
assert.doesNotMatch(worker, /여행 관리자만|함께 쓰는 사람/, '서버 오류 문구도 관리자와 구성원 용어로 통일');
assert.match(source, /id="deviceNameForm"[\s\S]*maxlength="40"/, '기기 이름 변경 폼과 길이 제한 제공');
assert.match(source, /days>=90\?'오래된 연결':!session\.current&&days>=30\?'30일 이상 사용하지 않음'/, '오래된 기기 안내 기준 제공');
assert.match(source, /management-primary-action[\s\S]*min-height:48px/, '관리 기본 버튼 규격 통일');
assert.match(source, /function myShareSettings/, '내 공유 정보 화면 제공');
assert.match(source, /id="displayNameForm"[\s\S]*maxlength="40"/, '표시명 변경 폼 제공');
assert.match(source, /function deviceLinkSheet[\s\S]*새 기기 연결 코드/, '공유 구성원 새 기기 연결 화면 제공');
assert.match(source, /trip-access-stack[\s\S]*관리자 권한 복구[\s\S]*data-open-device-link>새 기기에 연결/, '여행 목록의 연결 동작 문구와 버튼 간격 통일');
assert.match(source, /id="recoveryForm"[\s\S]*class="save management-primary-action">이 기기에 여행 연결[\s\S]*id="deviceLinkForm"[\s\S]*class="save management-primary-action">이 기기에 연결/, '두 연결 화면의 기본 버튼을 취소 버튼 규격과 통일');
assert.match(source, /function askConfirm/, '관리 작업은 앱 내부 확인 화면 사용');
assert.doesNotMatch(source, /dataset\.transferOwner\)\{if\(!confirm|dataset\.revokeMember\)\{if\(!confirm|dataset\.revokeSession\)\{[^}]*confirm/, '공유·기기 위험 작업에서 브라우저 확인창 제거');
assert.match(source, /id="collaborationLog"[^>]*>🕘 변경 내역 및 휴지통/, '설정에서 변경 내역과 휴지통 접근');
assert.match(source, /function collaborationSheet/, '변경 내역과 휴지통 모바일 관리 화면 제공');
assert.match(source, /data-restore-trash/, '삭제 항목 복원 동작 제공');
assert.match(source, /class="import-result-title"/, '분석 결과 제목에 전용 간격 클래스 적용');
assert.match(source, /\.import-result>\.review-callout\{margin:0 0 16px\}/, '저장 전 확인과 첫 입력 필드 사이 간격 제공');
const settingsSource = source.match(/function settings\(\)[\s\S]*?function searchResults/)?.[0] || '';
assert.doesNotMatch(settingsSource, /editCurrent|changeBg/, '설정에서 홈과 중복되는 여행 편집·배경 사진 메뉴 제거');
assert.match(settingsSource, /여행 관리[\s\S]*dataSafety[\s\S]*myShare[\s\S]*tripShare[\s\S]*collaborationLog[\s\S]*앱 기능[\s\S]*notify[\s\S]*allIcs[\s\S]*백업 및 복원[\s\S]*exportJson[\s\S]*importJson[\s\S]*앱 안내[\s\S]*초기화/, '설정 항목을 사용 목적과 우선순위에 따라 그룹화');
assert.match(settingsSource, /installed\?'':'<button id="installFromSettings"/, '설치된 앱에서는 중복 설치 메뉴를 숨김');
assert.match(source, /async function backupExportPreviewSheet/, 'JSON 백업 전에 포함 내용을 확인');
assert.match(source, /포함 원본[\s\S]*누락 원본[\s\S]*예상 용량/, '백업 전 원본 포함 수와 예상 용량 표시');
assert.match(source, /async function resetProtectionSheet/, '전체 초기화 전에 동기화·원본·최근 백업 상태 확인');
assert.doesNotMatch(settingsSource, /전체 초기화 \(두 번 탭\)/, '초기화 메뉴가 이전의 이중 탭 안내를 노출하지 않음');
assert.match(source, /if\(b\.dataset\.confirmReset!==undefined\)\{[^}]*state=sample\(\)[^}]*YeogiroStore\.persist/, '보호 화면에서 확인한 경우에만 전체 초기화');
assert.match(source, /dataset\.afterTrip==='backup'[\s\S]*backupExportPreviewSheet/, '여행 종료 화면의 백업도 사전 확인을 사용');
assert.match(source, /function previewFlightGroup/, '여러 항공편 분석 결과를 구간별로 확인');
assert.match(source, /function confirmFlightGroupImport/, '여러 항공편을 별도 데이터로 저장');
assert.match(source, /#analyzeDoc,#confirmImport,#confirmFlightGroup[^}]*width:100%[^}]*min-height:48px[^}]*border-radius:var\(--radius-control\)/, '여러 항공편 저장 버튼을 자동입력 공통 규격에 포함');
assert.match(source, /id="dataSafety">🗄️ 데이터 보관 상태/, '설정에서 데이터 보관 상태에 접근');
assert.match(source, /async function dataSafetySheet/, '동기화·원본·복구·백업 상태 화면 제공');
assert.match(source, /파일 원본[\s\S]*기기 저장공간/, '보관 상태에서 전체 원본과 브라우저 저장공간을 함께 표시');
assert.match(source, /1073741824[\s\S]*GB/, '큰 저장공간 용량은 GB 단위로 읽기 쉽게 표시');
assert.match(source, /data-safety-repair>파일 정보 정리/, '원본과 다른 메타데이터를 사용자가 정리 가능');
assert.match(source, /data-safety-files>예약 서류 확인/, '다른 기기에만 있는 원본은 서류함에서 확인 가능');
assert.match(source, /repairFileMetadata\(trip\(\)\)[\s\S]*YeogiroStore\.persist/, '파일 정보 정리 결과를 기존 동기화 흐름으로 저장');
assert.match(source, /data-safety-summary[\s\S]*safety-actions/, '데이터 보관 상태 모바일 UI 규격 제공');
assert.match(source, /data-safety-update>업데이트 확인/, '재설치 없는 앱 업데이트 확인 제공');
assert.match(source, /기기 보관 보호[\s\S]*data-safety-protect>기기 보관 보호하기/, '지원 브라우저에서 영구 저장 보호를 요청 가능');
assert.match(source, /function appUpdateSheet[\s\S]*data-update-apply>지금 업데이트/, '새 버전 상태와 데이터 보존 안내 화면 제공');
assert.match(source, /\.review-callout\.plain,\.review-callout\.app-update-callout\{border-left:0\}[\s\S]*review-callout app-update-callout/, '업데이트 안내 박스는 배경을 유지하고 왼쪽 선만 제거');
assert.match(source, /YeogiroPwa\.updateState\(YeogiroStore\.status\(\)/, '업데이트 직전에 동기화 상태를 다시 검증');
assert.match(source, /worker\.postMessage\(\{type:'SKIP_WAITING'\}\)/, '확인한 경우에만 대기 중인 버전을 활성화');
assert.match(source, /controllerchange[\s\S]*if\(!updateApplying\)return[\s\S]*location\.reload/, '사용자가 적용한 업데이트에서만 다시 불러오기');
assert.match(source, /register\('\/sw\.js\?v=48',[\s\S]*updateViaCache:'none'/, '최신 서비스 워커를 캐시 우회 등록');
assert.match(source, /앱 업데이트는 데이터를 지우지 않습니다/, '앱 삭제와 업데이트의 데이터 영향 안내');
assert.doesNotMatch(source, /dataset\.open==='settings'[\s\S]{0,240}docCabinet/, '설정 화면에 예약 서류함을 다시 삽입하지 않음');
assert.match(source, /renderDocumentPreview[\s\S]*data-doc-cabinet>서류함 전체 보기/, '홈 예약 서류에서 전체 서류함 접근 유지');
assert.match(source, /class="flight-airline"[\s\S]*class="flight-number"/, '항공사와 편명을 카드에서 두 줄로 구분');
assert.match(worker, /flights 배열에 실제 운항 구간별 객체를 순서대로 나눈다/, 'AI에 실제 운항 구간별 분리 지시');
assert.match(worker, /flightSource\.slice\(0,8\)\.map\(flightValue\)/, '서버에서 다중 항공편을 제한·정규화');

console.log('57 access management and extraction UI checks passed');
