import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync('index.html', 'utf8');
const sync = readFileSync('sync.js', 'utf8');
const worker = readFileSync('worker.js', 'utf8');

assert.equal((source.match(/function shareSettings/g) || []).length, 1, '공유 관리 화면 구현은 하나만 존재');
assert.equal((source.match(/function recoverSheet/g) || []).length, 1, '여행 복구 화면 구현은 하나만 존재');
assert.equal((source.match(/function recoveryResult/g) || []).length, 1, '복구키 결과 화면 구현은 하나만 존재');
assert.match(source, /<h2>여행 불러오기<\/h2>[\s\S]*새 기기에서 여행 불러오기/, '기존 여행 복구를 짧은 행동 중심 문구로 변경');
assert.doesNotMatch(source, /shareSettings\s*=\s*async|recoverSheet\s*=|recoveryResult\s*=/, '함수 재할당 오버라이드 제거');
assert.match(source, /function roleName\(role\)\{return role==='owner'\?'소유자'/, 'owner를 소유자로 표시');
assert.match(source, /function participantName[\s\S]*\['관리자','여행 관리자'\][\s\S]*\?'소유자'/, '기존 기본 표시명을 소유자 용어로 호환 표시');
assert.doesNotMatch(worker, /관리자만|구성원의 권한|구성원을 찾을 수 없습니다|최소 한 명의 관리자/, '서버 오류 문구도 소유자와 참여자 용어로 통일');
assert.match(source, /id="deviceNameForm"[\s\S]*maxlength="40"/, '기기 이름 변경 폼과 길이 제한 제공');
assert.match(source, /days>=90\?'오래된 연결':!session\.current&&days>=30\?'30일 이상 사용하지 않음'/, '오래된 기기 안내 기준 제공');
assert.match(source, /management-primary-action[\s\S]*min-height:48px/, '관리 기본 버튼 규격 통일');
assert.match(source, /function myShareSettings/, '내 정보 화면 제공');
assert.match(source, /id="displayNameForm"[\s\S]*maxlength="40"/, '표시명 변경 폼 제공');
assert.match(source, /profile-summary[\s\S]*표시명[\s\S]*권한[\s\S]*현재 기기[\s\S]*마지막 동기화/, '내 정보 핵심 상태 네 가지를 한눈에 표시');
assert.match(source, /소유자 관리[\s\S]*소유권 복구키[\s\S]*복구키 재발급/, '소유권 복구키를 내 정보의 소유자 전용 영역에 배치');
assert.match(source, /data-revoke-session[\s\S]*내 기기 관리/, '실제 세션 기반 기기 관리 제공');
assert.match(source, /function deviceLinkSheet[\s\S]*<h2>새 기기 연결<\/h2>[\s\S]*기존 기기에서 만든 연결 코드를 입력해 주세요/, '연결 링크 진입 시 연결 코드만 요청');
assert.doesNotMatch(source, /여행 ID 또는 연결 링크/, '기본 연결 화면에서 여행 ID 입력 제거');
assert.match(source, /기존 기기에서 연결 링크를 먼저 만들어 주세요[\s\S]*<summary>다른 방법으로 연결<\/summary>[\s\S]*여행 ID 직접 입력/, '직접 진입 시 링크 안내 후 기존 방식을 고급 옵션으로 제공');
assert.match(source, /name=\"connectToken\"[\s\S]*<label>연결 코드<\/label>/, '링크의 임시 토큰으로 여행을 자동 식별');
assert.match(source, /formatDeviceCode\(value\)[\s\S]*toUpperCase\(\)[\s\S]*replace\(\/\[\^A-Z2-9\]\/g,''\)[\s\S]*match\(\/.\{1,4\}\/g\)/, '연결 코드는 붙여넣기와 하이픈 자동 입력 지원');
assert.match(source, /function deviceCodeResult[\s\S]*15분 동안 한 번만[\s\S]*data-copy-device-link[\s\S]*data-share-device-link/, '기존 기기에서 만료 안내와 링크 복사·공유 제공');
assert.match(source, /function deviceLinkComplete[\s\S]*이 기기에 연결되었습니다\.[\s\S]*기존 여행과 자동으로 동기화됩니다\.[\s\S]*여행 열기/, '연결 완료 화면은 내부 식별자 없이 간단히 제공');
assert.match(sync, /params\.get\('connect_token'\)[\s\S]*deviceLinkToken/, '연결 링크 토큰을 시작 시 자동 인식');
assert.match(sync, /JSON\.stringify\(\{tripId,connectToken,code,\.\.\.deviceInfo\(\)\}\)/, '링크 토큰과 코드로 새 기기 세션 요청');
assert.match(worker, /connectId=`dlc_\$\{await hash\(connectToken\)\}`/, '연결 대상 임시 토큰은 기존 코드 ID에 해시로만 저장');
assert.match(worker, /connectUrl:`\/\?connect_token=\$\{encodeURIComponent\(connectToken\)\}`/, '연결 링크에 여행 ID나 접근 토큰 대신 임시 토큰만 포함');
assert.match(source, /trip-access-stack[\s\S]*data-open-recovery>여행 불러오기[\s\S]*data-open-device-link>새 기기에 연결/, '여행 목록에서 여행 불러오기와 새 기기 연결 제공');
assert.match(source, /id="recoveryForm"[\s\S]*소유권 복구키[\s\S]*class="save management-primary-action">여행 불러오기[\s\S]*id="deviceLinkForm"[\s\S]*class="save management-primary-action">이 기기에 연결/, '여행 불러오기와 기기 연결 기본 버튼 규격 통일');
assert.match(source, /<h2>공유 및 권한<\/h2>[\s\S]*<h3>참여자<\/h3>[\s\S]*<h3>새 초대<\/h3>[\s\S]*<h3>활성 초대 링크<\/h3>[\s\S]*<summary>관리<\/summary>/, '공유 및 권한 화면 정보 순서 유지');
assert.match(source, /id="inviteRole"[\s\S]*id="inviteUsage"[\s\S]*id="inviteExpiry"[\s\S]*value="1"[\s\S]*value="7" selected[\s\S]*value="30"/, '초대 권한·사용 방식·만료 선택과 7일 기본값 제공');
assert.match(source, /function inviteResultSheet[\s\S]*data-copy-invite-link>링크 복사[\s\S]*data-share-invite-link>공유/, '초대 생성 후 복사와 시스템 공유 제공');
assert.match(source, /data-change-member-role[\s\S]*참여자 권한 변경[\s\S]*askConfirm/, '권한 변경 전 앱 내부 재확인 제공');
assert.match(source, /id="timeOptionsToggle"[\s\S]*aria-expanded="\$\{expanded\}"[\s\S]*시간 세부 설정/, '종료·준비·고정 시간을 선택형 접기 영역으로 제공');
assert.match(source, /prepOptions=\[\[0,'없음'\],\[10,'10분'\],\[20,'20분'\],\[30,'30분'\],\[60,'1시간'\],\['custom','직접 입력'\]\]/, '준비시간 빠른 선택값과 직접 입력 제공');
assert.match(source, /name="preparationMinutes"[\s\S]*id="preparationHours"[\s\S]*id="preparationMinutePart"/, '시간·분 선택 결과를 기존 분 단위 필드로 유지');
assert.match(source, /function askConfirm/, '관리 작업은 앱 내부 확인 화면 사용');
assert.match(source, /class="activity-filters">\$\{filters\}/, '최근 변경에 간단한 필터 제공');
assert.match(source, /data-activity-filter="\$\{id\}"/, '필터 선택 상태를 버튼으로 전환');
assert.doesNotMatch(source, /최근 활동을 확인할 수 있습니다\./, '최근 변경 상단의 불필요한 설명 문구 제거');
assert.match(source, /최근 변경 기록을 표시합니다\./, '기록 범위는 하단 보조 문구로만 안내');
assert.match(source, /activityLimit\+=30;collaborationMarkup\(\)/, '기록이 많아도 한 번에 모두 렌더링하지 않음');
assert.match(source, /collaborationCache=await YeogiroStore\.collaborationLog\(\)/, '필터 전환 시 서버 기록을 다시 요청하지 않음');
assert.match(source, /\.page-tabs button\.on\{background:var\(--primary-blue\);color:#fff\}/, '선택한 일정·동선·경비 탭을 파란 배경과 흰색 글자로 표시');
assert.match(source, /function actorName\(row\)[\s\S]{0,320}return`\$\{raw\} 님`/, '휴지통과 기록에서 권한명 대신 참여자 이름 사용');
assert.match(source, /actorSubject\(row\)\{let name=actorName\(row\);return name==='나'\?'내가'/, '내가 삭제한 항목은 내 기준으로 표시');
assert.doesNotMatch(source, /display_name\|\|'참여자'\}\)\}이 삭제/, '어색한 조사 표기 제거');
assert.match(source, /data-empty-trash=\"\$\{data\.trash\.length\}\"[^`]*휴지통 비우기/, '소유자에게 휴지통 비우기 제공');
assert.match(source, /휴지통에 있는 \$\{b\.dataset\.emptyTrash\}개 항목을 완전히 삭제합니다/, '되돌릴 수 없는 삭제임을 확인 후 실행');
assert.match(source, /YeogiroStore\.emptyTrash\(\)/, '휴지통 비우기는 서버 API로 처리');
assert.match(sync, /trash`,\{method:'DELETE'\}/, '동기화 계층에서 휴지통 영구 삭제 요청');
assert.match(worker, /소유자만 휴지통을 비울 수 있습니다\./, '소유자만 휴지통을 비울 수 있음');
assert.match(worker, /DELETE FROM trip_trash WHERE trip_id=\? AND restored_at IS NULL/, '복원 대기 항목만 영구 삭제');
assert.match(worker, /휴지통 \$\{purged\}개 영구 삭제/, '휴지통 비우기도 기록에 남김');
assert.match(worker, /t\.deleted_by_member_id AS member_id/, '휴지통 항목의 삭제자 식별자 제공');
assert.doesNotMatch(source, /dataset\.transferOwner\)\{if\(!confirm|dataset\.revokeMember\)\{if\(!confirm|dataset\.revokeSession\)\{[^}]*confirm/, '공유·기기 위험 작업에서 브라우저 확인창 제거');
assert.match(source, /id="myShare"[^>]*>👤 내 정보/, '설정 메뉴에서 내 정보 명칭 사용');
assert.match(source, /id="tripShare"[^>]*>🔗 공유 및 권한/, '설정 메뉴에서 공유 및 권한 명칭 사용');
assert.match(source, /id="collaborationLog"[^>]*>🕘 기록 및 복구/, '설정에서 기록 및 복구 접근');
assert.match(source, /function collaborationSheet/, '기록 및 복구 모바일 관리 화면 제공');
assert.match(source, /<h2>기록 및 복구<\/h2>[\s\S]*<h3>휴지통<\/h3>[\s\S]*<h3>최근 변경<\/h3>/, '휴지통을 최근 변경보다 먼저 표시');
assert.match(source, /function primaryActivity[\s\S]*type==='file'&&action==='updated'[\s\S]*heroFileId/, '내부 대표사진과 파일 메타데이터 기록을 기본 목록에서 제외');
assert.match(source, /function groupActivities[\s\S]*600000/, '10분 이내 반복 기록 묶음 제공');
assert.match(source, /function activityListMarkup[\s\S]*slice\(0,20\)[\s\S]*더 보기/, '최근 변경 기본 20개와 더보기 제공');
assert.match(source, /data-restore-trash/, '삭제 항목 복원 동작 제공');
assert.match(source, /class="import-result-title"/, '분석 결과 제목에 전용 간격 클래스 적용');
assert.match(source, /\.import-result>\.review-callout\{margin:0 0 16px\}/, '저장 전 확인과 첫 입력 필드 사이 간격 제공');
const settingsSource = source.match(/function settings\(\)[\s\S]*?function searchResults/)?.[0] || '';
assert.doesNotMatch(settingsSource, /editCurrent|changeBg/, '설정에서 홈과 중복되는 여행 편집·배경 사진 메뉴 제거');
assert.match(settingsSource, /여행 관리[\s\S]*dataSafety[\s\S]*myShare[\s\S]*tripShare[\s\S]*collaborationLog[\s\S]*앱 기능[\s\S]*notificationSettings[\s\S]*preparation[\s\S]*allIcs[\s\S]*백업 및 복원[\s\S]*exportJson[\s\S]*importJson[\s\S]*앱 안내[\s\S]*초기화/, '설정 항목을 사용 목적과 우선순위에 따라 그룹화');
assert.match(settingsSource, /installed\?'':'<button id="installFromSettings"/, '설치된 앱에서는 중복 설치 메뉴를 숨김');
assert.match(source, /async function backupExportPreviewSheet/, 'JSON 백업 전에 포함 내용을 확인');
assert.match(source, /포함 원본[\s\S]*누락 원본[\s\S]*예상 용량/, '백업 전 원본 포함 수와 예상 용량 표시');
assert.match(source, /async function resetProtectionSheet/, '전체 초기화 전에 동기화·원본·최근 백업 상태 확인');
assert.doesNotMatch(settingsSource, /전체 초기화 \(두 번 탭\)/, '초기화 메뉴가 이전의 이중 탭 안내를 노출하지 않음');
assert.match(source, /if\(b\.dataset\.confirmReset!==undefined\)\{[^}]*state=sample\(\)[^}]*YeogiroStore\.persist/, '보호 화면에서 확인한 경우에만 전체 초기화');
assert.match(source, /phase==='after'[\s\S]*allDocuments\(\)\.length[\s\S]*여행 기록 보기[\s\S]*예약 서류 확인/, '여행 종료 화면은 여행 기록과 존재하는 예약 서류에 집중');
assert.doesNotMatch(source, /data-after-trip="backup"/, '여행 종료 카드에서 중복 JSON 백업 진입점 제거');
assert.match(settingsSource, /id="exportJson"[^>]*>⬇️ JSON 내보내기/, 'JSON 백업 기능은 설정의 백업 및 복원에서 유지');
assert.match(source, /function previewFlightGroup/, '여러 항공편 분석 결과를 구간별로 확인');
assert.match(source, /function confirmFlightGroupImport/, '여러 항공편을 별도 데이터로 저장');
assert.match(source, /#analyzeDoc,#confirmImport,#confirmFlightGroup[^}]*width:100%[^}]*min-height:48px[^}]*border-radius:var\(--radius-control\)/, '여러 항공편 저장 버튼을 자동입력 공통 규격에 포함');
assert.match(source, /id="dataSafety">🗄️ 데이터 보관 상태/, '설정에서 데이터 보관 상태에 접근');
assert.match(source, /async function dataSafetySheet/, '동기화·원본·복구·백업 상태 화면 제공');
assert.match(source, /파일 원본[\s\S]*'저장 공간'/, '보관 상태에서 전체 원본과 브라우저 저장 공간을 함께 표시');
assert.match(source, /1073741824[\s\S]*GB/, '큰 저장공간 용량은 GB 단위로 읽기 쉽게 표시');
assert.match(source, /data-safety-repair>파일 정보 정리/, '원본과 다른 메타데이터를 사용자가 정리 가능');
assert.match(source, /data-safety-files>예약 서류 확인/, '다른 기기에만 있는 원본은 서류함에서 확인 가능');
assert.match(source, /repairFileMetadata\(trip\(\)\)[\s\S]*YeogiroStore\.persist/, '파일 정보 정리 결과를 기존 동기화 흐름으로 저장');
assert.match(source, /data-safety-summary[\s\S]*safety-actions/, '데이터 보관 상태 모바일 UI 규격 제공');
assert.match(source, /data-safety-update>업데이트 확인/, '재설치 없는 앱 업데이트 확인 제공');
assert.match(source, /protectionState=[\s\S]*\['설정됨'[\s\S]*\['설정 필요'/, '파일 보관 설정 상태 문구 통일');
assert.match(source, /row\('📌','파일 보관 설정'[\s\S]*data-safety-protect>보관 설정/, '파일 보관 설정의 제목과 버튼 문구 통일');
assert.doesNotMatch(source, /기기 저장공간|기기 보관 보호|기기 보관 보호하기|파일 보관 보호/, '중복 명사와 오해하기 쉬운 이전 보관 문구 제거');
assert.match(source, /function appUpdateSheet[\s\S]*data-update-apply>지금 업데이트/, '새 버전 상태와 데이터 보존 안내 화면 제공');
assert.match(source, /\.review-callout\.plain,\.review-callout\.app-update-callout\{border-left:0\}[\s\S]*review-callout app-update-callout/, '업데이트 안내 박스는 배경을 유지하고 왼쪽 선만 제거');
assert.match(source, /YeogiroPwa\.updateState\(YeogiroStore\.status\(\)/, '업데이트 직전에 동기화 상태를 다시 검증');
assert.match(source, /worker\.postMessage\(\{type:'SKIP_WAITING'\}\)/, '확인한 경우에만 대기 중인 버전을 활성화');
assert.match(source, /controllerchange[\s\S]*if\(!updateApplying\)return[\s\S]*location\.reload/, '사용자가 적용한 업데이트에서만 다시 불러오기');
assert.match(source, /register\('\/sw\.js\?v=74',[\s\S]*updateViaCache:'none'/, '최신 서비스 워커를 캐시 우회 등록');
assert.match(source, /앱 업데이트는 데이터를 지우지 않습니다/, '앱 삭제와 업데이트의 데이터 영향 안내');
assert.doesNotMatch(source, /dataset\.open==='settings'[\s\S]{0,240}docCabinet/, '설정 화면에 예약 서류함을 다시 삽입하지 않음');
assert.match(source, /renderDocumentPreview[\s\S]*data-doc-cabinet>서류함 전체 보기/, '홈 예약 서류에서 전체 서류함 접근 유지');
assert.match(source, /class="flight-identity"[\s\S]*class="flight-airline"[\s\S]*class="flight-number"/, '항공사와 편명을 한 줄의 보조 정보로 표시');
assert.match(source, /\.flight \.flight-airline\{color:var\(--muted\);font-size:12px/, '항공사명이 노선보다 강조되지 않도록 위계를 낮춤');
assert.match(source, /function flightDetails[\s\S]*항공편 상세[\s\S]*flight-route flight-detail-route[\s\S]*flight-stop arrival/, '항공편 상세 요약을 출발·도착 좌우 배치로 표시');
assert.match(worker, /flights 배열에 실제 운항 구간별 객체를 순서대로 나눈다/, 'AI에 실제 운항 구간별 분리 지시');
assert.match(worker, /flightSource\.slice\(0,8\)\.map\(flightValue\)/, '서버에서 다중 항공편을 제한·정규화');

console.log('107 access management and extraction UI checks passed');
