const assert=require('node:assert/strict'),expense=require('../expense-logic.js');
assert.equal(expense.amountToMinor('12000','KRW'),12000,'KRW integer input');
assert.equal(expense.amountToMinor('12000','JPY'),12000,'JPY integer input');
assert.equal(expense.amountToMinor('12.34','USD'),1234,'USD cent input');
assert.equal(expense.amountToMinor('12.34','EUR'),1234,'EUR cent input');
assert.equal(expense.amountToMinor('150000','VND'),150000,'VND integer input');
assert.equal(expense.amountToMinor('12.345','USD'),null,'reject excess decimal precision');
assert.equal(expense.convertMinor(4800,'JPY','KRW',9200000),44160,'JPY conversion fixed to stored rate');
assert.equal(expense.convertMinor(1234,'USD','KRW',1380500000),17035,'USD cents convert without float drift');
assert.equal(expense.convertMinor(1,'USD','KRW',50000000),1,'conversion rounds a half minor unit up');
assert.equal(expense.rateMicrosFromQuote('100','JPY','920','KRW'),9200000,'direct JPY quote converts to micros');
assert.equal(expense.rateMicrosFromQuote('1','USD','0.92','EUR'),920000,'direct decimal-currency quote converts to micros');
assert.equal(expense.rateMicrosFromQuote('0','JPY','920','KRW'),null,'zero direct quote is invalid');
assert.deepEqual(expense.splitMinor(100,['c','a','b']),[{memberId:'a',shareMinor:34},{memberId:'b',shareMinor:33},{memberId:'c',shareMinor:33}],'remainder is deterministic and total preserved');
assert.equal(expense.splitMinor(100,['c','a','b']).reduce((n,x)=>n+x.shareMinor,0),100,'split sum equals original');
assert.deepEqual(expense.expenseShares({convertedMinor:101,shareMemberIds:['c','a','b']}),[{memberId:'a',shareMinor:34},{memberId:'b',shareMinor:34},{memberId:'c',shareMinor:33}],'only selected members receive deterministic shares');
const members=[{id:'a',name:'하건'},{id:'b',name:'동행자'}],two=[{id:'e1',category:'식비',convertedMinor:20000,paidByMemberId:'a',shareMemberIds:['a','b']}];
assert.deepEqual(expense.settle(two,members).transfers,[{fromMemberId:'b',fromName:'동행자',toMemberId:'a',toName:'하건',amountMinor:10000}],'two-person settlement');
const three=[{id:'e1',category:'식비',convertedMinor:60000,paidByMemberId:'a',shareMemberIds:['a','b','c']},{id:'e2',category:'교통',convertedMinor:30000,paidByMemberId:'a',shareMemberIds:['a','b','c']}];
const threeResult=expense.settle(three,[{id:'a',name:'A'},{id:'b',name:'B'},{id:'c',name:'C'}]);
assert.equal(threeResult.transfers.length,2,'three-person settlement minimizes transfers');
assert.equal(threeResult.transfers.reduce((n,x)=>n+x.amountMinor,0),60000,'settlement transfer total matches debts');
assert.equal(threeResult.members.reduce((n,x)=>n+x.balanceMinor,0),0,'member balances conserve total');
assert.equal(threeResult.categories.find(x=>x.category==='식비').amountMinor,60000,'category summary');
const four=expense.settle([{id:'e1',category:'식비',convertedMinor:101,paidByMemberId:'a',shareMemberIds:['a','b','c','d']}],[{id:'a',name:'A'},{id:'b',name:'B'},{id:'c',name:'C'},{id:'d',name:'D'}]);
assert.equal(four.transfers.length,3,'four-person settlement uses one transfer per debtor');
assert.equal(four.transfers.reduce((n,x)=>n+x.amountMinor,0),75,'four-person settlement conserves total debt');
assert.equal(four.members.find(x=>x.memberId==='a').balanceMinor,75,'specific payer balance is retained');
assert.equal(four.members.reduce((n,x)=>n+x.balanceMinor,0),0,'four-person balances conserve total');
assert.equal(expense.settlementFingerprint(two),expense.settlementFingerprint(structuredClone(two)),'stable settlement fingerprint');
assert.match(expense.formatMinor(-1000,'KRW'),/-.*1,000/,'negative settlement balances remain visible');
console.log('26 expense calculation checks passed');
