const assert=require('node:assert/strict');
const n=require('../notification-logic.js');
const items=[{id:'a',day:'2026-09-01',time:'13:00',name:'점심',reminderMinutes:0},{id:'b',day:'2026-09-01',time:'15:00',name:'바나힐',place:'바나힐',move:'자동차',preparationMinutes:10,reminderMinutes:30}];
const legs={b:{durationMinutes:20,label:'자동차'}};
assert.deepEqual(n.normalizeSettings({morning:true}),{departure:true,schedule:true,weather:true,preTrip:true,morning:true});
assert.equal(n.stableId('t','b','schedule','x'),'t:b:schedule:x');
assert.equal(n.scheduleReminderMinutes(items[1]),30);
let events=n.itemEvents({tripId:'t',day:'2026-09-01',nowMinutes:870,items,legs,windowMinutes:1});
assert.equal(events.length,1);assert.equal(events[0].type,'combined');assert.match(events[0].title,/이동/);
assert.equal(n.itemEvents({tripId:'t',day:'2026-09-01',nowMinutes:840,items,legs:{}}).length,0);
let overdue=n.overdueEvent({tripId:'t',day:'2026-09-01',nowMinutes:875,item:items[1],previous:items[0],leg:legs.b});assert.equal(overdue.type,'departure');
assert.equal(n.overdueEvent({tripId:'t',day:'2026-09-01',nowMinutes:900,item:items[1],previous:items[0],leg:legs.b}),null);
const outdoor={name:'바나힐 야외 투어',cat:'관광'};
assert.equal(n.significantWeatherChange({precipitationProbability:20},{precipitationProbability:80},outdoor).kind,'rain');
assert.equal(n.significantWeatherChange({precipitationProbability:20},{precipitationProbability:30},outdoor),null);
assert.equal(n.significantWeatherChange({precipitationProbability:20},{precipitationProbability:80},{name:'호텔',cat:'숙소'}),null);
assert.equal(n.pending([{id:'x'}],{x:Date.now()}).length,0);
assert.equal(Object.keys(n.pruneHistory({a:1,b:2,c:3},null,2)).length,2);
console.log('12 notification logic checks passed');
