import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const source = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const renderer = source.match(/function preparationSheet\(\)[\s\S]*?\nfunction notificationPrefs/)?.[0] || '';

assert.match(renderer, /status==='required'/, '확인 필요 상태를 별도로 분류');
assert.match(renderer, /status==='optional'/, '선택 사항 상태를 별도로 분류');
assert.match(renderer, /출발 전 확인 · \$\{required\.length\}건/, '실제 확인 필요 항목만 집계');
assert.doesNotMatch(renderer, />확인<\/button>/, '반복 확인 버튼 제거');
assert.match(renderer, /data-prep-action=.*prep-chevron/, '행 전체 바로가기와 chevron 유지');
assert.match(renderer, /선택 사항 \$\{optional\.length\}건/, '선택 사항 기본 접힘');
assert.match(renderer, /완료 \$\{done\.length\}건/, '완료 항목 기본 접힘');
assert.match(renderer, /summary\.flights\?/, '0건 항공편 요약 숨김');
assert.match(renderer, /아직 등록된 여행 정보가 없습니다/, '빈 요약 상태 제공');
assert.match(renderer, /role="progressbar"/, '준비 진행률 접근성 제공');
assert.match(renderer, /prep-menu-actions/, '정렬과 삭제를 overflow 메뉴로 이동');
assert.doesNotMatch(renderer, /prep-state[^<]*\">! 확인 필요/, '행마다 확인 필요 문구를 반복하지 않음');
assert.match(renderer, /날씨 · 예보 준비 중/, '예보 전 날씨를 중립 요약으로 표시');
assert.match(renderer, /required/, '빈 준비물 입력은 required로 차단');
assert.match(source, /if\(!title\)return/, '공백 준비물 입력도 저장 전에 차단');
assert.match(renderer, /class="prep-important">중요/, '중요 상태를 독립 배지로 표시');
assert.match(renderer, /<h3>준비물<\/h3><small>\$\{progress\.done\} \/ \$\{progress\.total\} 완료/, '준비물 제목에 실시간 진행률 표시');
assert.match(renderer, /class="prep-scope-chip"/, '개인 공용 선택을 중립 칩으로 표시');
assert.match(renderer, /prepAddScope==='shared'\?'selected'/, '추가 후 선택한 공용 범위 유지');
assert.match(renderer, /class="prep-add-button"[^>]*disabled>\+<\/button>/, '빈 입력에서 더하기 버튼 비활성화');
assert.match(renderer, /add\.disabled=!input\.value\.trim\(\)/, '입력 내용에 따라 더하기 버튼 활성화');
assert.match(renderer, /enterkeyhint="done"/, '모바일 키보드 완료 힌트 제공');
assert.match(source, /\$\('#prepAdd input'\)\?\.focus\(\)/, '연속 입력을 위해 추가 후 포커스 복원');
assert.match(source, /\.prep-section\+\.addline\{margin-top:20px\}/, '날씨 요약과 닫기 버튼 사이 간격 확보');
assert.match(source, /grid-template-columns:minmax\(0,1fr\) 74px 42px/, '입력창 우선 단일 행 레이아웃');
console.log('25 preparation UI checks passed');
