import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync('index.html', 'utf8');
const worker = readFileSync('worker.js', 'utf8');
const sync = readFileSync('sync.js', 'utf8');
const travel = readFileSync('travel-logic.js', 'utf8');
const migration = readFileSync('migrations/0011_item_route_controls.sql', 'utf8');
const sw = readFileSync('sw.js', 'utf8');

assert.match(source, /data-page="overview"[^>]*>동선</, '기존 오버뷰 탭을 동선 화면으로 재사용');
assert.match(source, /id="map"[\s\S]{0,300}routeSvg[\s\S]{0,200}mapMarks/, '하루 전체 지도와 경로 레이어 제공');
assert.match(source, /function dayRouteStops\(\)/, '선택 날짜의 지도 정류장을 한 곳에서 구성');
assert.match(source, /type:'item'/, '일정 정류장 포함');
assert.match(source, /type:'lodging'/, '숙소 정류장 포함');
assert.match(source, /type:'airport'/, '실제 항공편 날짜의 공항 정류장 포함');
assert.match(source, /AIRPORT_COORDS=/, '지원 공항의 검증된 좌표 사용');
assert.match(source, /flight\.arriveDate===selected/, '도착일에 도착 공항 연결');
assert.match(source, /flight\.departDate===selected/, '출국일에 출발 공항 연결');
assert.match(source, /move:'항공',fixed:true/, '출발 공항과 도착 공항 사이는 지상 OSRM 경로로 계산하지 않음');
assert.match(source, /events\]\.sort\(\(a,b\)=>\(a\.time/, '같은 날 출발·도착도 항공편 시간순으로 배치');
assert.match(source, /id="includeLodgingReturn"/, '숙소 복귀는 선택 옵션');
assert.match(source, /includeLodgingReturn&&lodging/, '복귀 선택 때만 마지막 숙소 추가');

assert.match(source, /<div class="pin-dot">\$\{i\.type==='lodging'\?'⌂':i\.type==='airport'\?'✈':n\+1\}/, '일정 번호와 숙소·공항 표식 구분');
assert.match(source, /fitMap\(list\)/, '하루 전체 위치를 기준으로 지도 범위 조정');
assert.match(source, /class="pin[^`]*active/, '선택한 마커 강조');
assert.match(source, /data-pin="\$\{i\.id\}"/, '마커와 정류장 ID 연결');
assert.match(source, /data-route-stop="\$\{esc\(stop\.id\)\}"/, '동선 목록에서 같은 정류장 선택 가능');
assert.match(source, /journeyDetail/, '선택 정류장 상세 영역 제공');
assert.match(source, /journey-leg-copy[\s\S]{0,140}예상 이동 경로/, '선택 지점의 다음 이동정보 표시');

assert.match(source, /routeBase\(profile\.key\)/, '기존 라우팅 프로필 재사용');
assert.match(travel, /routing\.openstreetmap\.de/, '라우팅 주소는 travel logic의 기존 OSRM 계열 사용');
assert.match(source, /fetch\('\/api\/route\?'\+params\)/, '브라우저 CORS 차이를 피하도록 Worker 경유');
assert.match(worker, /async function routeForecast\(request,env,url\)/, 'Worker에 경로 프록시 제공');
assert.match(worker, /radiuses=5000;5000/, '건물 좌표도 주변 도로에 스냅해 경로 계산');
assert.match(worker, /router\.project-osrm\.org/, '자동차 경로는 기존 OSRM 계열 대체 엔드포인트 제공');
assert.match(source, /result\.geometry\.coordinates\.map/, '직선이 아니라 API 경로 geometry 사용');
assert.match(source, /profile\.routable/, '지원 가능한 이동수단만 자동 라우팅');
assert.match(source, /unsupported:true/, '대중교통 등 미지원 수단은 가짜 시간 없이 구분');
assert.match(source, /외부 지도에서 경로 확인/, '미지원 이동수단은 외부 길찾기로 안내');
assert.match(source, /data-route-dir=/, '각 주요 정류장에서 외부 길찾기 제공');
assert.match(source, /google\.com\/maps\/dir/, '앱 내부 내비게이션 대신 외부 지도 사용');

assert.match(source, /name="move"/, '구간별 이동수단을 다음 일정에 저장');
assert.match(source, /name="moveMinutes"/, '구간 이동시간 수동 설정 지원');
assert.match(source, /draft\.moveMinutes=/, '수동 이동시간을 여행 데이터에 저장');
assert.match(source, /Number\.isInteger\(b\.moveMinutes\)/, '수동값이 자동 라우팅보다 우선');
assert.match(source, /manual:true/, '수동 이동시간 표시 상태 보존');
assert.match(source, /name="fixed"/, '고정 일정 설정 제공');
assert.match(source, /<span>시간 세부 설정<\/span>/, '고정 일정 선택을 기본 날짜 입력에서 세부 설정으로 이동');
assert.match(source, /시간 변경이 어려운 일정[\s\S]{0,80}동선 추천에서 이 시간을 보호/, '고정 일정이 필요한 이유를 사용자 언어로 안내');
assert.match(source, /draft\.fixed=fd\.get\('fixed'\)==='on'/, '고정 여부를 여행 데이터에 저장');
assert.match(source, /고정 일정이나 종료시간이 있는 일정은 시간을 직접 편집/, '고정·종료시간 일정의 간편 재배치 차단');

assert.match(source, /routeSummary\(list,routes\)/, '총 이동시간과 거리 계산 결과 재사용');
assert.match(source, /예상 이동/, '실시간 교통으로 오해하지 않는 표현');
assert.match(source, /assessGap\(list\[index-1\],stop,leg\)/, '기존 충돌 판정 재사용');
assert.match(source, /출발 권장/, '다음 시작시간에서 이동·여유시간을 빼 출발 권장 표시');
assert.match(source, /routeWarning/, '경고 우선순위를 순수 로직에서 결정');
assert.match(source, /routeWeather\(stop\)/, '저장된 날씨를 구간 경고에 연결');
assert.match(source, /Intl\.DateTimeFormat\('en-CA',\{timeZone:forecast\.timezone/, '현재·다음 일정과 지금 위치를 여행지 현지 시간대로 계산');
assert.match(source, /routeSuggestion\(list\)/, '숙소·공항을 포함한 전체 동선으로 개선 제안 계산');
assert.match(source, /추천 순서 적용/, '사용자 확인으로만 추천 순서 적용');
assert.match(source, /askConfirm\(\{title:'추천 순서 적용'/, '자동 재배치 금지');
assert.match(source, /routeCache\.clear\(\);save\(\);render/, '순서 변경 후 경로·충돌·합계 재계산');

assert.match(source, /routeCacheGet\(key\)/, '메모리 전에 IndexedDB 경로 캐시 확인');
assert.match(source, /routeCachePut\(key,leg\)/, '계산한 경로를 IndexedDB 캐시에 저장');
assert.match(source, /Date\.now\(\)-memory\.savedAt<7\*86400000/, '메모리 경로 캐시도 유효기간 검증');
assert.match(sync, /route:\$\{key\}/, '경로 캐시는 영구 여행 데이터와 분리');
assert.match(sync, /7\*86400000/, '경로 캐시에 유한 만료 정책 적용');
assert.match(source, /offline:!navigator\.onLine/, '오프라인 캐시 결과 상태 표시');
assert.match(source, /저장된 이동시간/, '오프라인 이동시간을 최신처럼 표시하지 않음');
assert.match(source, /경로를 갱신하려면 인터넷 연결이 필요합니다\./, '오프라인 경로 갱신 차단');
assert.match(source, /id="routeRetry"/, '라우팅 장애 재시도 제공');
assert.match(source, /id="routeRetry" aria-label="경로 새로고침"[\s\S]{0,220}class="route-refresh-icon"[\s\S]{0,160}<span>경로<\/span>/, '긴 다시 계산 문구 대신 새로고침 아이콘과 경로 문구 사용');
assert.match(source, /routeRetry\.loading \.route-refresh-icon\{animation:route-refresh-spin/, '경로 갱신 중 새로고침 아이콘 회전');
assert.match(source, /function animateTransportAlong\(geometry,move\)/, '선택 구간에서만 이동수단 아이콘이 경로를 따라 이동');
assert.match(source, /routeMotionFrame=requestAnimationFrame\(step\)/, '이동 애니메이션은 requestAnimationFrame으로 실행');
assert.match(source, /function cancelRouteMotion\(\)\{routeMotionToken\+\+/, '경로 변경 시 이전 애니메이션 정리');
assert.match(source, /document\.visibilityState!=='visible'/, '화면 밖이나 백그라운드에서는 이동 애니메이션 중지');
assert.match(source, /path\.animate\(\[\{strokeDasharray:[\s\S]{0,260}duration:700/, '지도 진입과 전환 시 경로선을 순서대로 그림');
assert.match(source, /\.pin \.pin-label\{opacity:0[\s\S]{0,180}\.pin\.active \.pin-label/, '현재 장소 이름만 펼쳐 지도 혼잡을 줄임');
assert.match(source, /@media\(prefers-reduced-motion:reduce\)[\s\S]{0,320}animation:none!important/, '동작 줄이기 설정에서는 지도 애니메이션 비활성화');
assert.match(source, /routeDayTitle'\)\.textContent=fmt\(selected\)/, '날짜 제목에서 중복 동선 문구 제거');
assert.match(source, /class="route-return-toggle"[\s\S]{0,120}숙소로 돌아오기/, '숙소 복귀 옵션을 작은 선택 버튼으로 표시');
assert.match(source, /route-return-toggle'\)\.classList\.toggle\('hide',!lodgingAvailable\)/, '숙소가 있는 날짜에만 복귀 옵션 표시');
assert.match(source, /route-stop-head>span>small\{margin-top:6px;line-height:1\.4\}/, '장소명과 하단 시간·주소 사이 간격 확보');
assert.match(source, /reference=\(\)=>\(\{\.\.\.fallback,failed:true/, '지원 경로 API 실패 시 직선거리 참고값을 명시적으로 구분');
assert.match(source, /background-image:url\('\$\{proxy\}'\),url\('\$\{direct\}'\)/, '지도 타일은 깨진 이미지 대신 Worker와 OSM 이중 배경으로 렌더');
assert.match(source, /\/api\/map-tile\/\$\{z\}\/\$\{x\}\/\$\{y\}\.png\?v=3/, '이전 손상 타일 캐시를 우회');
assert.match(source, /leg\.reference\?'직선거리 기준 '/, '경로 실패 시 참고값임을 명확히 표시');
assert.match(source, /route-number\{display:inline-grid[\s\S]{0,100}width:22px;height:22px/, '일정 번호 원을 텍스트 크기에 맞게 축소');
assert.match(source, /석굴로238[\s\S]{0,100}\[35\.7948033,129\.3491954\][\s\S]{0,100}숲머리길159[\s\S]{0,100}\[35\.8430039,129\.2530179\]/, '석굴암과 토함의 잘못 저장된 좌표를 실제 위치로 복구');
assert.match(source, /\.pin\{position:absolute;width:auto;height:auto;padding:0;border:0;background:transparent;-webkit-appearance:none/, 'iOS 기본 버튼 배경이 지도 핀 주변을 가리지 않음');
assert.match(source, /route-summary>span\{display:grid[\s\S]{0,100}gap:5px/, '장소 수와 경로 상태 문구 사이 간격 확보');
assert.match(source, /#map\{height:34vh;min-height:280px;max-height:350px\}/, '모바일 지도 높이를 축소해 일정 정보를 먼저 노출');
assert.match(source, /\.map-frame\.expanded #map\{height:72vh/, '필요할 때만 지도를 크게 확장');
assert.match(source, /id="mapExpand"[^>]*>지도 크게 보기</, '지도 크게 보기 진입 제공');
assert.match(source, /\.route-summary\{order:2\}[\s\S]{0,90}\.map-frame\{order:4/, '동선 요약과 현재·다음 일정을 지도보다 먼저 배치');
assert.match(source, /route-summary-title">오늘 동선</, '하루 이동 규모를 지도 상단에서 요약');
assert.match(source, /modes\.length===1\?`\$\{modes\[0\]\} 이동 기준`/, '요약에 이동수단 기준 표시');
assert.match(source, /label\.textContent=`\$\{index\+1\} · \$\{list\[index\]\.name\}`/, '선택된 마커에서만 장소명을 노출');
assert.match(source, /closest\('\[data-pin\]'\)[\s\S]{0,240}moveJourneyTo\(index\)[\s\S]{0,90}focusRouteSelection\(index,true\)/, '마커 선택 시 해당 일정 카드로 연동');
assert.match(source, /closest\('\[data-route-stop\]'\)[\s\S]{0,220}moveJourneyTo\(index\)/, '일정 카드 선택 시 지도 포커스 연동');
assert.match(source, /last\?'마지막 일정':`\$\{journey\+1\}번째 일정`/, '개발자식 2\/2 대신 사용자 언어로 순서 표현');
assert.match(source, /data-route-leg="\$\{index-1\}"[\s\S]{0,260}\$\{distanceText\}/, '일정 리스트에서도 구간 이동시간과 거리 표시');
assert.match(source, /journey-primary-actions[\s\S]{0,260}data-journey-dir[\s\S]{0,240}data-journey-detail/, '현재·다음 일정 중심의 길찾기와 상세보기 제공');
assert.match(source, /\.datechip:not\(\.on\)\{color:#4e5968\}/, '선택하지 않은 날짜 대비 강화');
assert.match(source, /function transportType\(move=''\)[\s\S]{0,240}자전거[\s\S]{0,90}버스[\s\S]{0,140}자동차\|택시/, '이동수단별 아이콘 자동 선택');
assert.match(source, /stroke-width="1\.8" stroke-linecap="round"/, '게임풍 블록 대신 플랫 아이콘 사용');
assert.doesNotMatch(source, /fill="#f2b48c"/, '기존 게임 캐릭터 그래픽 제거');
assert.match(source, /\.routeSvg path\.selected-leg\{opacity:1/, '선택 구간만 강조하고 나머지 경로는 약하게 표시');
assert.match(source, /route-estimate-badge">예상 이동 경로</, '실제 위치가 아니라 예상 이동 경로임을 명시');
assert.match(source, /\.character\{width:32px;height:32px/, '현재 위치 아이콘을 일정 마커보다 작게 표시');
assert.match(source, /directional=\['car','bus','bicycle'\]\.includes\(transportType\(move\)\)/, '방향성 있는 이동수단만 경로 방향으로 회전');
assert.match(source, /timedTarget=next&&\(next\.type==='item'\|\|next\.id\.startsWith\('airport-depart-'\)\)/, '숙소 정렬용 임시 시간으로 출발 권장을 만들지 않음');
assert.match(source, /if\(map\.tileHtml!==html\)\{map\.tileHtml=html;tiles\.innerHTML=html\}/, '같은 타일 구성은 재사용해 선택 시 지도 깜빡임 방지');
assert.match(source, /\.no-pin-enter \.pin\{animation:none\}/, '선택 전환에서는 마커 등장 애니메이션 반복 안 함');

assert.match(source, /위치 없음 · \$\{missing\.length\}개/, '좌표 없는 일정도 동선 목록에서 유지');
assert.match(source, /data-route-location=/, '좌표 없는 일정의 위치 설정 진입');
assert.match(source, /draft\.place!==oldPlace[\s\S]{0,80}draft\.lat=null/, '주소 변경 시 이전 좌표 무효화');
assert.match(source, /if\(draft\.address!==old\?\.address\)/, '숙소 주소 변경 시 좌표 무효화');

assert.match(worker, /fixed:Boolean\(x\.fixed\)/, '서버가 고정 일정 값을 정규화');
assert.match(worker, /moveMinutes:Number\.isSafeInteger/, '서버가 수동 이동시간 범위를 검증');
assert.match(worker, /fixed_schedule,move_minutes/, 'D1 저장 구문에 동선 필드 포함');
assert.match(migration, /fixed_schedule INTEGER NOT NULL DEFAULT 0/, '고정 일정 D1 마이그레이션');
assert.match(migration, /move_minutes INTEGER CHECK/, '수동 이동시간 D1 마이그레이션');
assert.match(sync, /item\.fixed=false/, '기존 로컬 일정에 안전한 기본값 추가');
assert.match(source, /role!=='viewer'\?`<button data-route-shift/, 'viewer에게 순서 편집 버튼 미노출');
assert.match(source, /보기 전용 참여자는 일정 순서를 변경할 수 없습니다\./, '직접 이벤트에서도 viewer 수정 차단');
assert.match(worker, /if\(!canEdit\(member\)\)return json\(\{error:'보기 전용 여행은 수정할 수 없습니다\.'/,'서버 revision 업데이트 권한 유지');
assert.match(sw, /url\.hostname === 'tile\.openstreetmap\.org'/, '기존 지도 타일 캐시 유지');
assert.match(sw, /url\.pathname\.startsWith\('\/api\/map-tile\/'\)/, '프록시 지도 타일도 제한된 오프라인 캐시에 저장');

console.log('121 route optimization integration checks passed');
